### ISSUE TITLE
Free API KEY

### ISSUE THREAD

**Issue by lynn-fisher** [stelace/heroes-platform-demo#347]
Hi there, I noticed some references to a free api_key on the readme and the documentation at 'https://stelace.com/docs/getting-started.html#_1-get-your-free-api-keys' but I am not sure where to get that from and cant find a place to register, can only find login for existing users. Can you advise please?

**Comment by abruere** [comment]
Hi, sorry for the long-overdue answer !
We no longer offer free API keys but please feel free to install open-source [Stelace server](https://github.com/stelace/stelace) to get an API key as suggested in the updated "Getting started" guide.
